import type { Metadata } from 'next'
import { Mona_Sans } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/homepage/footer'
import { Toaster } from '@/components/ui/sonner'

const monaSans = Mona_Sans({
	variable: '--font-mona-sans',
	weight: ['400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${monaSans.className} antialiased`}>
				<Navbar />
				{children}
				<Footer />
				<Toaster />
			</body>
		</html>
	)
}
